zooniverse/zoo-notes

- package.json
- yarn.lock
This PR adds the deployment/publishing script.
- Run `npm run deploy` to build and deploy files to `https://zoo-notes.zooniverse.org/` (requires Zooniverse S3 access, of course)
- Note that this is a production build, but on the live site you can switch environments using the classic `?env=staging` trick
- We're still using `publisssh` right now, but when I have time I want to revisit this and use https://github.com/mediamonks/s3-batch-upload as Jim recommended
> Add deployment script

- package.json
- src/components/SubjectViewer/SubjectViewer.js
- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/AggregationsPane.js
- src/pages/ViewPage.js
- src/stores/AggregationsStore.js
- src/stores/AppStore.js
- yarn.lock
This PR adds a system that fetches and displays aggregated annotations for a given Subject.
- Aggregated annotations data is fetched from Caesar via AggregationsStore.
- Aggregated annotations data is displayed on top of the Subject image via AggregationsPane .
- Currently only **point tasks** are properly aggregated.
- (And even then, the point annotations have to be keyed to task T0, tool 0. See note below.)
- Example (staging): http://localhost:3000/view/workflow/3438/subject/133565 (compare to results at https://caesar-staging.zooniverse.org/workflows/3438/subjects/133565)
⚠️ Please note:
- The method for extracting Aggregations Data from the Caesar results is very very very haphazardously hardcoded and brittle. Any change to the structure of the workflow or Caesar results will pretty …
> Add Aggregations Pane

- package.json
- src/App.js
- src/components/SubjectViewer/components/AggregationsPane.js
- src/components/WorkflowObserver/WorkflowObserver.js
- src/components/WorkflowObserver/index.js
- src/pages/SubjectPage.js
- src/pages/WorkflowPage.js
- yarn.lock
This PR adds a Workflow Observer, which monitors recent Classifications (or rather, Subjects being classified) for a given workflow.
Intended Usage: this allows a user (or a teachers in a classroom) to classify Subjects on one browser tab, then switch to another tab with the Workflow Observer to see the Subject they just classified.
- To observe a specific workflow (e.g. 1234): `https://zoo-notes.zooniverse.org/view/workflow/1234`
- To observe ALL workflows: `https://zoo-notes.zooniverse.org/view/workflow`
- The Workflow Observer uses a Pusher stream.
- **External Requirement:** the Zooniverse Pusher stream
- ⚠️ Currently, I'm only able to fetch streams from Panoptes, not Panoptes-staging. I need to check the Zooniverse Pusher account to see if there IS something there.
> Add Workflow Observer

- src/components/SubjectViewer/SubjectViewer.js
- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/AggregationsPane.js
- src/components/SubjectViewer/components/ViewerControls.js
- src/stores/AggregationsStore.js
- src/stores/ViewerStore.js
This PR updates the aggregations pane and adds controls for the Subject Viewer.
- the Aggregations Store now cleanly separates 'extracts' (raw classifications) and 'reductions' (actual aggregations) into their own arrays
- the Subject Viewer has been updated so it displays two kinds of 'aggregation data' - the extracts and the reductions. Both types of data points have their own colour (and exist on their own AggregationPane component)
- The Subject Viewer now has actual buttons to control panning, zooming, and toggling the visibility of extracts/reductions.
> Update Aggregations and add Viewer Controls 

- src/App.js
- src/components/LargeMessageBox/LargeMessageBox.js
- src/components/LargeMessageBox/index.js
- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/ViewerControls.js
- src/components/WorkflowInputBox/WorkflowInputBox.js
- src/components/WorkflowInputBox/index.js
- src/components/WorkflowObserver/WorkflowObserver.js
- src/pages/HomePage.js
- src/pages/MainLayout.js
- src/pages/WorkflowPage.js
This PR adds a number of UI/UX improvements that's meant to help users navigate the website.
- A home page has been added (path: `/`, of course) with instructions for first-time users.
- A main menu has been added to the header.
- The path to 'observe all workflows' page has changed from `/view/workflow` to `/view`
- Status/Error messages are now added to the Workflow Page and Subject Page.
- [Accessibility] Buttons that rely on images now have alt tags.
> Improve UI/UX for website navigation

- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/ViewerControls.js
This PR adds a 'paging' system on the Subject Viewer. This is useful for multi-image Subjects.
- If a Subject has more than 1 image, the Viewer Controls displays a selectable dropdown, starting with "page 1"
- Users can change the 'page' (i.e. change the index of the currently viewed image) by selecting from said dropdown.
- Gods help you in the Subject consists of non-image media, though.
Possible improvements:
- Add a 'loading image...' message to address the times when the Subject Viewer is trying to fetch an image file and is visibly blank.
- Also add an 'ERROR COULD NOT FETCH IMAGE' message.
> Add page selection (for multi-image Subjects)

- src/components/WorkflowObserver/WorkflowObserver.js
- src/helpers/localStorage.js
This PR updates the Workflow Observer component so it saves recently-classified Subjects to local storage, and loads recently-classified Storage from local storage when the page boots up.
- Additionally, the Workflow Observer now opens Subjects in a new window/tab.
> Add memory to Workflow Observer

- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/AggregationControls.js
- src/components/WorkflowObserver/WorkflowObserver.js
- src/helpers/localStorage.js
- src/stores/AggregationsStore.js
This PR adds the Aggregation Controls panel, to the right-side of the Subject Viewer component.
- At the moment, the Aggregation Controls only displays the summary of the Subject's annotations+aggregations.
- A new 'stats' object has been added to the Aggregations Store for this purpose
Additionally:
- A 'Clear' button has been added to the Workflow Observer, allowing users to reset the list of observed Subjects.
> Add Aggregation controls

- src/components/SubjectViewer/components/AggregationControls.js
- src/stores/AggregationsStore.js
This PR fixes an issue when Caesar extracts Classifications that have no annotations (e.g., the Subject has no viruses, so no marks were placed)
- When Caesar extracts a Classification with no annotations, the `.extracts` will record that Classification, but as an empty object (no `frame0` child)
- The AggregationsStore made the mistake of assuming that the `frame0` child object would always exist.
- Simple fix was to add an existence check.
> Fix "null Classifications" scenario

- src/components/SubjectViewer/components/AggregationControls.js
- src/stores/AggregationsStore.js
This PR fixes a major issue in the Aggregations store: when processing [point-type reductions](https://aggregation-caesar.zooniverse.org/reducers.html#point-reducer-dbscan), the store was reading the _constituent raw points of a potential cluster_ as the aggregated points, instead of reading the _actual cluster points._
This, of course, resulted in the viewer showing an incorrect number of "aggregated points".
Incorrect:
_In this example (pre-fix), 15 raw points map to 15 aggregated points. This doesn't make sense, since the number of aggregated points should be far fewer than the number of raw points._
Correct:
_In this example (post-fix), 15 raw points map to 1 aggregated point. This is because from all the raw input provided, only 1 cluster (consensus of input) can be found._
- The …
> Fix incorrect mapping of clusters and reductions

- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/AggregationControls.js
- src/components/SubjectViewer/components/WorkflowControls.js
- src/stores/SubjectStore.js
- src/stores/ViewerStore.js
- src/stores/WorkflowStore.js
Currently, the Zoo Notes Subject Viewer system (and the relevant data stores) makes one huge assumption: the selected Workflow will have exactly one Task, and that Task will be a Drawing Task with exactly 1 Point-type subtask.
This PR attempts to expand the scope of what the Subject Viewer can handle, first by allowing users to select which Task they want.
- A new Workflow Controls component has been added to the Subject Viewer, which allows users to switch between Workflow Tasks
- The Workflow Store now keeps track of `workflow.taskId`, which defines the ID of the currently selected Workflow Task.
- The Workflow Store now has methods for easily determining the currently selected Task's data and type.
Misc:
- The `viewer.page` property of the Viewer store - which keeps track of the …
> Add Workflow Controls

- src/components/AggregationsViewer/AggregationsViewer.js
This is a minor update that ensures that when the selected Task is of type 'single', the Aggregations Viewer starts off in the expanded view.
- Note the way the React useEffect hook is structured; the 'start with expanded view' will trigger when either...
- The Aggregation Viewer initialises and the Workflow resource loads. (selectedTaskType changes from 'undefined' to 'single'), or
- The selected Task changes from a non-SAQ Task to an SAQ Task. (e.g. selectedTaskType changes from 'drawing' to 'single')
> Single Answer Question Task starts with expanded view

- src/components/AggregationsViewer/components/PieChart.js
- src/components/AggregationsViewer/components/SingleTask.js
- src/components/SubjectViewer/components/WorkflowControls.js
This PR adds a pie chart to the SingleTask (Single Answer Question Task) subcomponent of the Aggregations Viewer.
- The 'Chart' tab has been added to the SingleTask subcomponent.
- The text in the 'Q&A' tab is larger when expanded.
- The SingleTask component now shows percentages where possible.
> Pie Charts and various SingleTask improvements

- bin/upload.js
- package.json
Move the S3 upload config into its own script. Add Cache-Control headers to give us 60s caching of index.html and 604800s (7 days) for all other static assets.
> Add Cache-Control headers to uploads

- package.json
- src/components/SubjectViewer/SubjectViewer.js
- yarn.lock
Upgrade `react-scripts` to version 4. Patch everything else to the latest allowed version.
Fix a hooks error in the subject viewer which was caught, I think, by the bump to react 16.14.
Closes https://github.com/zooniverse/how-to-zooniverse/issues/80
> [Security] Upgrade dependencies

- package.json
Setting `CI=false` for the build so that the GA production deploy works and doesn't fail on linter warnings.
> Turn off the linter failures so build works

- yarn.lock
This is a fresh install of all dependencies to their latest allowed versions. It fixes a security warning for y18n < 4.0.1.
Closes https://github.com/zooniverse/how-to-zooniverse/issues/92
> Upgrade all the things

- src/experimental-sloan/components/ClusterViewer1.jsx
- src/experimental-sloan/data/subjects.json
- src/experimental-sloan/helpers/stopEvent.js
- src/experimental-sloan/pages/ExperimentsPage.js
Part of the SLOAN Grant Experiment. See #58 for context
This PR improves the ClusterViewer v1 with a Subject Inspector, and improves styles.
- A ClusterViewer should be navigable with either keyboard or mouse.
- Clicking on a Subject (a galaxy) should bring up some (currently fake) details about said galaxy, mined from the metadata. (Presumably in the future, we'd find more interesting info on individual galaxies from the planned cluster API.)
Merging as an experimental build.
The experiment will be viewable at https://zoo-notes.zooniverse.org/experimental
> SLOAN Grant Experiment - ClusterViewer v1 and Subject Inspector

- src/components/AggregationsViewer/components/SingleTask.js
- src/components/SubjectViewer/SubjectViewer.js
- src/components/SubjectViewer/components/WorkflowControls.js
- src/components/WorkflowObserver/WorkflowObserver.js
This fixes a few linter warnings during the build.
- Remove redundant escape characters from regular expressions.
- Force workflow IDs to ints before comparing them.
- Move external dependencies inside the effect for the `onWheel` handler in the subject viewer.
> APPEASE THE LINTER!

- src/App.js
- src/App.test.js
- src/components/AggregationsViewer/AggregationsViewer.js
- src/components/AggregationsViewer/components/DrawingTask.js
- src/components/AggregationsViewer/components/PieChart.js
- src/components/AggregationsViewer/components/SingleTask.js
- src/components/LargeMessageBox/LargeMessageBox.js
- src/components/SubjectViewer/SubjectViewer.js
- src/components/SubjectViewer/SubjectViewerContainer.js
- src/components/SubjectViewer/components/AggregationsPane.js
- src/components/SubjectViewer/components/ViewerControls.js
- src/components/SubjectViewer/components/WorkflowControls.js
- src/components/WorkflowInputBox/WorkflowInputBox.js
- src/components/WorkflowObserver/WorkflowObserver.js
- src/helpers/withThemeContext.js
- src/index.js
- src/pages/HomePage.js
- src/pages/MainLayout.js
- src/pages/SubjectPage.js
- src/pages/WorkflowPage.js
`react-scripts` 4 supports the new JSX transform, so we can remove the `React` global from our JSX files.
> Remove the React global

- src/App.js
- src/components/WorkflowInputBox/WorkflowInputBox.js
- src/pages/MainLayout.js
- src/pages/SubjectPage.js
- src/pages/WorkflowPage.js
Upgrade to the new hooks API in `react-router` 6, following [the migration guide for v5](https://reactrouterdotcom.fly.dev/docs/en/v6/upgrading/v5).
- replace `<Switch>` with `<Routes>`.
- replace `useHistory` with `useNavigate`.
- remove `withRouter`.
- remove `exact` from routes.
- replace `component` with `element` in routes.
- replace `match` with `useParams`.
> Upgrade to `react-router` v6

- src/hooks/index.js
- src/hooks/useCaesar.js
- src/hooks/usePanoptes.js
- src/pages/SubjectPage.js
- src/stores/AggregationsStore.js
- Add `useCaesar` and `usePanoptes` hooks to fetch aggregations, subjects and workflows.
- Move the Caesar graphQL query out of the store and into the `useCaesar` hook.
> Refactor data-fetching with hooks

- src/hooks/useCaesar.js
Fixes a React render error by wrapping aggregations store updates inside a `useEffect` hook, so that they run outside the main render cycle.
Closes #92.
> Wrap store updates in a useEffect hook

- README.md
- package.json
Turn on HTTPS for local development. I don't think the app uses Panoptes secure cookies at the moment, but this enables them if they are needed eg. to request private resources.
> Enable HTTPS for local development

- src/components/AggregationsViewer/AggregationsViewer.js
- src/components/AggregationsViewer/components/SingleTask.js
- src/hooks/useCaesar.js
- src/hooks/usePanoptes.js
- src/pages/SubjectPage.js
Add extractor and reducer keys to Caesar queries, but only for workflows with more than one task. Assume that the Caesar key names will always match the task identifier eg. `init`, `T1`, `T2` etc.
Remove `selectedTaskIndex` from the task logic, since reductions will only be fetched for a single task now.
Closes #78.
> Add Caesar extractor and reducer keys

- src/hooks/useCaesar.js
- src/stores/AggregationsStore.js
- src/stores/AppStore.js
Add an `autorun` reaction to the root store, which observes the subject, workflow and downloaded Caesar data, and runs `aggregations.extractData()` when all three are ready.
> Automate data extraction in the Aggregations store

- package.json
- src/hooks/useCaesar.js
- src/stores/AggregationsStore.js
- yarn.lock
This PR updates PJC to 4.1.0 for security reasons.
Additionally, this fixes an issue where the Subject page crashes if a Subject doesn't have an Aggregation.
- If a Subject doesn't have an aggregation, the results return 404
- Prior to be3163c, this is handled OK, with the error message being shown on the Subject page.
- However, something changed since that commit - the error message is an _object_ instead of the expected _string,_ which causes `useCaesar()`'s `applySnapshot` to crash.
- Fix is to add a simple check to make sure the snapshot passed to applySnapshot() is valid.
> Update panoptes-client to 4.1.0 and fix useCaesar() crashing on error objects

- src/hooks/useCaesar.js
SWR 2 no longer destructures fetcher key arrays as function args (see https://github.com/vercel/swr/pull/1864.) Here, we pass the Caesar parameters straight through to the data fetcher as an object.
See #162.
> Update data fetchers for SWR 2
